"""Shared UI sizing and performance constants."""

APP_MIN_WIDTH = 900
APP_MIN_HEIGHT = 600
SIDEBAR_WIDTH = 72
HEADER_HEIGHT = 64
CORNER_RADIUS = 16
MAX_VISIBLE_MESSAGES = 100
ASSET_CACHE_LIMIT = 32
ANIMATION_FPS_IDLE = 12
ANIMATION_FPS_ACTIVE = 30
